### ISSUE TITLE
Fade transition error

### ISSUE THREAD

**Issue by simonewebdesign** [glslio/glsl-transition#7]
Just ran the tests and got this error:

fade transition
should correctly fade ‣
Error: Uncaught AssertionError: ending 'to' image (http://greweb.me/glsl-transition/test/bundle.js:7325)
    at global.onerror (http://greweb.me/glsl-transition/test/mocha/mocha.js:5513:10)

Chrome Version 32.0.1700.102 on OS X Mavericks

**Comment by gre** [comment]
Just released a new version of glsl-transition.
there is no more tests for now since the codebase is very small and mostly rely on `gl-shader` (not much to test).
The new library version should be simpler to use and more robust and efficient.
